import { useMemo, useState } from 'react'
import { defaultSettings, holidays, timetable } from './data'
import { attendanceAfter, attendanceCategoryId, calculateTotals, categoryAudit, categoryLabel, dayName, formatDate, generateOccurrences, isCompleted, isEligible } from './logic'
import { subjects, type ClassOccurrence, type Page, type StudentSettings } from './types'

const storage = { settings: 'itnu-settings', bunks: 'itnu-bunks' }
const readSettings = (): StudentSettings => { try { return { ...defaultSettings, ...JSON.parse(localStorage.getItem(storage.settings) || '{}') } } catch { return defaultSettings } }
const readBunks = (): Set<string> => { try { return new Set(JSON.parse(localStorage.getItem(storage.bunks) || '[]')) } catch { return new Set() } }
const today = defaultSettings.simulationDate

function App() {
  const [page, setPage] = useState<Page>('Dashboard')
  const [settings, setSettings] = useState<StudentSettings>(readSettings)
  const [bunked, setBunked] = useState<Set<string>>(readBunks)
  const [selectedDate, setSelectedDate] = useState(today)
  const totals = useMemo(() => calculateTotals(settings, bunked), [settings, bunked])
  const occurrences = useMemo(() => generateOccurrences(settings, settings.simulationDate), [settings])
  const selectedDay = occurrences.filter((occurrence) => occurrence.date === selectedDate)
  const saveBunks = (next: Set<string>) => { setBunked(next); localStorage.setItem(storage.bunks, JSON.stringify([...next])) }
  const toggleBunk = (id: string) => { const next = new Set(bunked); next.has(id) ? next.delete(id) : next.add(id); saveBunks(next) }
  const bunkAllToday = () => { const next = new Set(bunked); occurrences.filter((item) => item.date === settings.simulationDate && item.attendanceBearing && isCompleted(item, settings)).forEach((item) => next.add(item.id)); saveBunks(next) }
  const updateSettings = (next: StudentSettings) => { setSettings(next); localStorage.setItem(storage.settings, JSON.stringify(next)) }
  const reset = () => { localStorage.removeItem(storage.settings); localStorage.removeItem(storage.bunks); setSettings(defaultSettings); setBunked(new Set()) }

  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark">NU</div><div><strong>ITNU</strong><span>Attendance Planner</span></div></div>
      <div className="student-chip"><span className="eyebrow">CURRENT PROFILE</span><strong>26ITC067 - 26ITC090</strong><span>Division C / Group I / C3</span></div>
      <nav>{(['Dashboard', 'Attendance', 'Bunk Planner', 'Calendar', 'Timetable', 'Settings', 'Sources & Rules'] as Page[]).map((item, index) => <button className={page === item ? 'nav-item active' : 'nav-item'} onClick={() => setPage(item)} key={item}><span className="nav-number">0{index + 1}</span>{item}</button>)}</nav>
      <div className="sidebar-footer"><span className="status-dot" /> Live calculation<br /><small>Local data only</small></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><div><span className="eyebrow">B.TECH / FIRST YEAR / SEMESTER I</span><h1>{page}</h1></div><div className="date-pill"><span className="status-dot" /> {settings.calculationMode === 'asOfNow' ? 'As of now' : 'End of today'} / {formatDate(settings.simulationDate)}</div></header>
      {page === 'Dashboard' && <Dashboard settings={settings} totals={totals} occurrences={occurrences} bunked={bunked} onBunk={toggleBunk} onBunkAll={bunkAllToday} onNavigate={setPage} />}
      {page === 'Attendance' && <Attendance totals={totals} threshold={settings.threshold} />}
      {page === 'Bunk Planner' && <Planner settings={settings} totals={totals} occurrences={occurrences} bunked={bunked} onBunk={toggleBunk} onBunkAll={bunkAllToday} />}
      {page === 'Calendar' && <Calendar occurrences={occurrences} bunked={bunked} selectedDate={selectedDate} onDate={setSelectedDate} />}
      {page === 'Timetable' && <Timetable settings={settings} />}
      {page === 'Settings' && <Settings settings={settings} onSave={updateSettings} onReset={reset} />}
      {page === 'Sources & Rules' && <><Rules settings={settings} occurrences={occurrences} /><CategoryAudit settings={settings} occurrences={occurrences} /></>}
    </main>
  </div>
}

function Metric({ label, value, detail, accent = '' }: { label: string; value: string | number; detail?: string; accent?: string }) { return <div className={`metric ${accent}`}><span>{label}</span><strong>{value}</strong>{detail && <small>{detail}</small>}</div> }
function Badge({ children, tone = '' }: { children: React.ReactNode; tone?: string }) { return <span className={`badge ${tone}`}>{children}</span> }
function pct(value: number | null) { return value === null ? 'No data' : `${value.toFixed(1)}%` }
function status(value: number | null, threshold: number) { return value === null ? ['NO DATA', 'neutral'] : value < threshold ? ['BELOW 85%', 'danger'] : value < threshold + 5 ? ['WARNING', 'warning'] : ['SAFE', 'safe'] }

function Dashboard({ settings, totals, occurrences, bunked, onBunk, onBunkAll, onNavigate }: { settings: StudentSettings; totals: ReturnType<typeof calculateTotals>; occurrences: ClassOccurrence[]; bunked: Set<string>; onBunk: (id: string) => void; onBunkAll: () => void; onNavigate: (page: Page) => void }) {
  const todayClasses = occurrences.filter((item) => item.date === settings.simulationDate)
  const attendedUnits = totals.reduce((sum, item) => sum + item.attended, 0)
  const heldUnits = totals.reduce((sum, item) => sum + item.held, 0)
  const affected = todayClasses.filter((item) => item.attendanceBearing && isCompleted(item, settings))
  return <div className="page-stack">
    <section className="hero-grid"><div className="hero-copy"><span className="eyebrow lime">{dayName(new Date(`${settings.simulationDate}T12:00:00`).getDay()).toUpperCase()} / {formatDate(settings.simulationDate).toUpperCase()}</span><h2>Make today<br /><em>count.</em></h2><p>Know exactly what a missed class costs before you make the call.</p><button className="primary-button" onClick={() => onNavigate('Bunk Planner')}>Open bunk planner <span>{'->'}</span></button></div><div className="hero-note"><span className="eyebrow">ATTENDANCE STANDARD</span><strong>{settings.threshold}%</strong><p>Minimum in every attendance-bearing course.</p><div className="rule-line" /><span className="eyebrow">LIVE SINCE</span><strong className="small-strong">01 AUG 2026</strong></div></section>
    <section className="metrics"><Metric label="Currently held" value={heldUnits} detail="attendance occurrences" accent="lime-accent" /><Metric label="Attended" value={attendedUnits} detail={`${heldUnits ? ((attendedUnits / heldUnits) * 100).toFixed(1) : '0.0'}% overall`} /><Metric label="Bunked" value={heldUnits - attendedUnits} detail="occurrences absent" accent="peach-accent" /><Metric label="Today" value={affected.length} detail={`${affected.length} completed classes`} /></section>
    <section className="content-grid"><div className="panel"><div className="panel-heading"><div><span className="eyebrow">TUESDAY, 15 SEP</span><h3>Today's classes</h3></div><button className="bunk-button" onClick={onBunkAll}>Bunk all today</button></div><div className="class-list">{todayClasses.map((item) => <ClassRow key={item.id} item={item} bunked={bunked.has(item.id)} onBunk={() => onBunk(item.id)} completed={isCompleted(item, settings)} />)}</div></div><div className="panel"><div className="panel-heading"><div><span className="eyebrow">COURSE HEALTH</span><h3>Where you stand</h3></div><button className="text-button" onClick={() => onNavigate('Attendance')}>View all {'->'}</button></div><div className="health-list">{totals.map((item) => { const [label, tone] = status(item.percentage, settings.threshold); return <div className="health-row" key={item.attendanceCategoryId}><div><strong>{item.categoryLabel}</strong><span>{item.attended}/{item.held} attended</span></div><div className="health-right"><strong>{pct(item.percentage)}</strong><Badge tone={tone}>{label}</Badge></div></div> })}</div></div></section>
  </div>
}

function ClassRow({ item, bunked, onBunk, completed = false, showStatus = true }: { item: ClassOccurrence; bunked: boolean; onBunk: () => void; completed?: boolean; showStatus?: boolean }) { const canBunk = item.attendanceBearing && completed; const state = !item.attendanceBearing ? 'Excluded' : bunked ? 'Bunked' : completed ? 'Completed - Attended' : 'Upcoming'; return <div className={`class-row ${bunked ? 'is-bunked' : ''}`}><div className="time">{item.startTime}<small>{item.endTime}</small></div><div className="class-name"><strong>{item.subject}</strong><span>{item.type}{item.batch ? ` / ${item.batch}` : ''}</span>{showStatus && <small className={`class-status ${bunked ? 'status-bunked' : completed ? 'status-completed' : 'status-upcoming'}`}>{state}</small>}</div><div className="units">{item.attendanceBearing ? '1 attendance' : 'excluded'}</div>{canBunk && <button className="bunk-button" onClick={onBunk}>{bunked ? 'Undo' : 'Bunk'}</button>}</div> }

function Attendance({ totals, threshold }: { totals: ReturnType<typeof calculateTotals>; threshold: number }) { return <div className="page-stack"><div className="section-intro"><div><span className="eyebrow lime">CATEGORY-WISE SOURCE OF TRUTH</span><h2>Attendance, without<br />the guesswork.</h2></div><p>Lectures and labs remain independent attendance categories. Bunking one never changes the other.</p></div><div className="table-panel"><div className="table-head"><span>Category</span><span>Held</span><span>Attended</span><span>Absent</span><span>Attendance</span><span>Safe skips</span><span>Status</span></div>{totals.map((item) => { const [label, tone] = status(item.percentage, threshold); return <div className="table-row" key={item.attendanceCategoryId}><strong>{item.categoryLabel}</strong><span>{item.held}</span><span>{item.attended}</span><span className={item.absent ? 'red-text' : ''}>{item.absent}</span><strong>{pct(item.percentage)}</strong><span>{item.safeSkips ?? '-'}</span><Badge tone={tone}>{label}</Badge></div> })}</div><p className="footnote">Safe skips are calculated independently for every lecture, lab/tutorial, Yoga and Disaster Management category.</p></div> }

function Planner({ settings, totals, occurrences, bunked, onBunk, onBunkAll }: { settings: StudentSettings; totals: ReturnType<typeof calculateTotals>; occurrences: ClassOccurrence[]; bunked: Set<string>; onBunk: (id: string) => void; onBunkAll: () => void }) { const todayClasses = occurrences.filter((item) => item.date === settings.simulationDate && item.attendanceBearing && isCompleted(item, settings)); const simulations = todayClasses.map((item) => { const total = totals.find((entry) => entry.attendanceCategoryId === item.attendanceCategoryId)!; return { item, current: total, after: attendanceAfter(total, 1, settings.threshold) } }); const wholeDay = totals.map((total) => ({ total, after: attendanceAfter(total, todayClasses.filter((item) => item.attendanceCategoryId === total.attendanceCategoryId).length, settings.threshold) })).filter(({ after }) => after.attended >= 0 && after.attended !== undefined)
  return <div className="page-stack"><div className="section-intro"><div><span className="eyebrow lime">BUNK PLANNER / SIMULATION</span><h2>What if I don't<br />go today?</h2></div><p>Explore the mathematical impact first. Nothing is saved until you press Bunk on a class.</p></div><section className="planner-grid"><div className="panel"><div className="panel-heading"><div><span className="eyebrow">INDIVIDUAL CLASSES</span><h3>Today's impact</h3></div><button className="bunk-button" onClick={onBunkAll}>Bunk all today</button></div><div className="simulation-list">{simulations.map(({ item, current, after }) => <div className="simulation-row" key={item.id}><div><strong>{item.subject} {item.type === 'Lab/tutorial' ? 'Lab' : item.type === 'Regular lecture' ? 'Lecture' : ''}</strong><span>{item.startTime} - {item.endTime} / 1 attendance</span></div><div className="simulation-values"><span>{pct(current.percentage)}</span><b>{'->'}</b><span className={after.below ? 'red-text' : 'green-text'}>{pct(after.percentage)}</span></div><button className="bunk-button" onClick={() => onBunk(item.id)}>{bunked.has(item.id) ? 'Undo' : 'Bunk'}</button></div>)}</div></div><div className="panel dark-panel"><div className="panel-heading"><div><span className="eyebrow lime">CATEGORY SIMULATION</span><h3>If every class is missed</h3></div></div><div className="whole-day-list">{wholeDay.map(({ total, after }) => <div className="whole-day-row" key={total.attendanceCategoryId}><div><strong>{total.categoryLabel}</strong><span>{pct(total.percentage)} {'->'} {pct(after.percentage)}</span></div><Badge tone={after.below ? 'danger' : 'safe'}>{after.below ? 'Below 85%' : 'Still safe'}</Badge></div>)}</div></div></section></div> }

function Calendar({ occurrences, bunked, selectedDate, onDate }: { occurrences: ClassOccurrence[]; bunked: Set<string>; selectedDate: string; onDate: (date: string) => void }) { const days = [...new Set(occurrences.map((item) => item.date))].slice(-28); const dayItems = occurrences.filter((item) => item.date === selectedDate); return <div className="page-stack"><div className="section-intro compact"><div><span className="eyebrow lime">ACADEMIC CALENDAR</span><h2>September 2026</h2></div><p>Tap any date to inspect its eligible timetable. Library is shown but never counted.</p></div><div className="calendar-grid">{days.map((date) => <button className={selectedDate === date ? 'calendar-day selected' : 'calendar-day'} onClick={() => onDate(date)} key={date}><span>{new Date(`${date}T12:00:00`).toLocaleDateString('en-IN', { weekday: 'short' })}</span><strong>{date.slice(-2)}</strong><small>{occurrences.filter((item) => item.date === date && item.attendanceBearing).length} classes</small></button>)}</div><div className="panel"><div className="panel-heading"><div><span className="eyebrow">SELECTED DATE</span><h3>{formatDate(selectedDate)}</h3></div></div><div className="class-list">{dayItems.length ? dayItems.map((item) => <ClassRow key={item.id} item={item} bunked={bunked.has(item.id)} onBunk={() => undefined} />) : <div className="empty-state">No classes scheduled.</div>}</div></div></div> }

function Timetable({ settings }: { settings: StudentSettings }) { const entries = timetable.filter((entry) => isEligible(entry, settings)); return <div className="page-stack"><div className="callout"><strong>Eligibility rules</strong><span>Regular lectures use Division/Group. Lab/tutorial uses {settings.labBatch}. Yoga uses {settings.yogaBatch}. Every attendance-bearing timetable session counts once.</span></div><div className="week-grid">{[1, 2, 3, 4, 5, 6].map((day) => <div className="day-column" key={day}><div className="day-title">{dayName(day).slice(0, 3).toUpperCase()}<small>{entries.filter((item) => item.weekday === day).length} entries</small></div>{entries.filter((item) => item.weekday === day).map((item) => <div className={`timetable-card ${item.type === 'Library' ? 'library-card' : item.type === 'Yoga' ? 'yoga-card' : item.type === 'Lab/tutorial' ? 'lab-card' : ''}`} key={item.id}><span>{item.startTime} - {item.endTime}</span><strong>{item.subject}</strong><small>{item.type}{item.batch ? ` / ${item.batch}` : ''}</small><b>{item.attendanceBearing ? '1x' : '0x'}</b></div>)}</div>)}</div></div> }

 function Settings({ settings, onSave, onReset }: { settings: StudentSettings; onSave: (settings: StudentSettings) => void; onReset: () => void }) { const [draft, setDraft] = useState(settings); return <div className="page-stack"><div className="section-intro compact"><div><span className="eyebrow lime">STUDENT CONFIGURATION</span><h2>Your setup</h2></div><p>Changes recalculate eligibility and live attendance immediately after saving.</p></div><div className="settings-grid"><div className="panel form-panel"><span className="eyebrow">STUDENT PROFILE</span><div className="form-grid"><label>Division<select value={draft.division} onChange={(e) => setDraft({ ...draft, division: e.target.value })}><option>C</option></select></label><label>Group<select value={draft.group} onChange={(e) => setDraft({ ...draft, group: e.target.value })}><option>I</option></select></label><label>Lab/tutorial batch<select value={draft.labBatch} onChange={(e) => setDraft({ ...draft, labBatch: e.target.value })}><option>C1</option><option>C2</option><option>C3</option></select></label><label>Yoga batch<select value={draft.yogaBatch} onChange={(e) => setDraft({ ...draft, yogaBatch: e.target.value })}><option>CT1</option><option>CT2</option><option>CT3</option></select></label></div></div><div className="panel form-panel"><span className="eyebrow">CALCULATION</span><div className="form-grid"><label>Threshold (%)<input type="number" min="1" max="100" value={draft.threshold} onChange={(e) => setDraft({ ...draft, threshold: Number(e.target.value) })} /></label><label>Attendance start<input type="date" value={draft.startDate} onChange={(e) => setDraft({ ...draft, startDate: e.target.value })} /></label><label>As-of date<input type="date" value={draft.simulationDate} onChange={(e) => setDraft({ ...draft, simulationDate: e.target.value })} /></label><label>Calculation mode<select value={draft.calculationMode} onChange={(e) => setDraft({ ...draft, calculationMode: e.target.value as StudentSettings['calculationMode'] })}><option value="asOfNow">As of now</option><option value="endOfToday">End of today</option></select></label></div></div></div><div className="settings-actions"><button className="primary-button" onClick={() => onSave(draft)}>Save settings <span>{'->'}</span></button><button className="text-button danger-button" onClick={onReset}>Reset local data</button></div></div> }

function Rules({ settings, occurrences }: { settings: StudentSettings; occurrences: ClassOccurrence[] }) { const exclusions = timetable.filter((entry) => !isEligible(entry, settings)); return <div className="page-stack"><div className="section-intro compact"><div><span className="eyebrow lime">TRANSPARENCY</span><h2>Sources & rules</h2></div><p>Attendance is calculated from one generated occurrence list and independent attendance categories.</p></div><div className="rules-grid">{[['01', 'Independent categories', 'Every lecture, lab/tutorial and Yoga category has its own held, attended, absent, percentage and safe-skip calculation.'], ['02', 'Eligibility', 'Regular lectures use Division/Group. Lab/tutorial entries use the selected batch. Yoga uses the selected Yoga batch.'], ['03', 'Automatic attendance', 'Completed attendance-bearing classes are attended by default. A saved bunk affects only its unique occurrence ID.'], ['04', 'Occurrence count', 'Every attendance-bearing timetable session is exactly one attendance count, regardless of how long its timetable block lasts.'], ['05', 'Holiday source', holidays.size ? [...holidays].join(', ') : 'No academic holiday dataset is present in this project; no holidays are invented.'], ['06', 'Eligibility exclusions', exclusions.length ? exclusions.map((entry) => `${entry.subject} ${entry.batch || entry.type}`).join(', ') : 'None in the supplied timetable data.']].map(([number, title, body]) => <div className="rule-card" key={number}><span>{number}</span><h3>{title}</h3><p>{body}</p></div>)}</div></div> }

function CategoryAudit({ settings, occurrences }: { settings: StudentSettings; occurrences: ClassOccurrence[] }) { const audits = categoryAudit(settings, settings.simulationDate); return <div className="page-stack"><div className="audit-panel"><div className="panel-heading"><div><span className="eyebrow lime">ITNU ODD TERM 2026-27 AUDIT</span><h3>Independent dated category totals</h3></div></div>{audits.map((audit) => <details key={audit.categoryId}><summary>{audit.label} <span>{audit.finalUnits} final / {audit.normalUnits} normal occurrences</span></summary><p><strong>Counted:</strong> {audit.countedEntries.map((item) => `${item.date} 1 occurrence`).join(', ') || 'None'}<br /><strong>Excluded:</strong> {audit.excludedEntries.map((item) => `${item.date} 1 occurrence - ${item.reason}`).join(', ') || 'None'}</p></details>)}<div className="audit-notes"><strong>Calendar:</strong> Teaching 03-Aug-2026 to 05-Dec-2026. Sessional 06-Oct to 09-Oct. Diwali vacation 06-Nov to 13-Nov. Listed holidays are excluded dynamically.<br /><strong>Attendance count:</strong> Every attendance-bearing session contributes exactly one count, regardless of duration. <strong>Library:</strong> not present in the authoritative weekly timetable and contributes 0 attendance.</div></div></div> }

export default App
